{% set name = "click-shell" %}
{% set version = "2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce0c91faae284c41a39bec966f928791ad4a45763755445f1fe2041fd091aa37

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - click >=7.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - click_shell

about:
  home: https://github.com/clarkperkins/click-shell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An extension to click that easily turns your click app into a shell utility'
  doc_url: https://click-shell.readthedocs.io/
  dev_url: https://github.com/clarkperkins/click-shell

extra:
  recipe-maintainers:
    - holgern
    - jan-janssen
